name: Get affected files
description: Check the affected files in the pull request to then tun "nx affected" commands
runs:
  using: composite
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5.0.1
