name: Get affected files
description: Check the affected files in the pull request to then tun "nx affected" commands
runs:
  using: composite
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v4
