name: Linting and Formatting
description: 'Lint and format the affected files in the pull request with Biome'
runs:
  using: composite
  steps:
    - name: Sets the base and head SHAs required for the nx affected
      uses: nrwl/nx-set-shas@v3

    - name: Checkout the code
      shell: bash
        # This line is needed for nx affected to work when CI is running on a PR
      run: git branch --track main origin/main

    - name: Linting 🪮 and Formatting 🖊️
      shell: bash
      run: pnpm nx affected run-many -t lint format
