name: PR validation
run-name: ${{ github.actor }} is running PR validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - '!release-please--branches--main'
    paths-ignore:
      - 'CHANGELOG.md'
      - .release-please-manifest.json
  merge_group:
    types: [checks_requested]

concurrency:
  cancel-in-progress: true
  group: '${{ github.workflow }} @ ${{ github.ref }}'

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare

  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    needs: [prepare]
    permissions:
      contents: read
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set environment and install dependencies
        uses: ./.github/actions/prepare

      - name: Conventional Commits
        uses: ./.github/actions/conventional-commits

  lint-format:
    name: Linting and formatting
    runs-on: ubuntu-latest
    needs: [prepare]
    permissions:
      contents: read
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set environment and install dependencies
        uses: ./.github/actions/prepare

      - name: Get affected files
        uses: ./.github/actions/get-affected-files

      - name: Linting and formatting
        uses: ./.github/actions/lint-format

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: [prepare]
    permissions:
      contents: read
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set environment and install dependencies
        uses: ./.github/actions/prepare

      - name: Get affected files
        uses: ./.github/actions/get-affected-files

      - name: Run unit tests
        uses: ./.github/actions/unit-test

  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run actionlint
        run: |
          bash <(curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/914e7df21a07ef503a81201c76d2b11c789d3fca/scripts/download-actionlint.bash) 1.7.12
          ./actionlint -color

  ci-validation:
    name: CI validation
    needs: [prepare, conventional-commits, lint-format, unit-tests, actionlint]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check jobs for errors
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { default: checkJobsForErrors } = await import('${{ github.workspace }}/.github/workflows/js/check-for-errors.mjs');
            const jobs = ${{ toJSON(needs) }};
            checkJobsForErrors({ core, jobs });
