name: Create a release 🚀
run-name: ${{ github.actor }} is releasing a new version
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/release.yaml
      - 'CHANGELOG.md'

permissions:
  contents: write
  pull-requests: write

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  e2e:
    name: End to end test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set environment and install dependencies
        uses: ./.github/actions/prepare

      - name: 🎭 Install Playwright
        run: pnpm exec playwright install

      - name: Run e2e test
        run: pnpm nx e2e website --reporter=github
        env:
          NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID}}
          NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN}}
          NEXT_PUBLIC_GIVEBUTTER_API_KEY: ${{ secrets.NEXT_PUBLIC_GIVEBUTTER_API_KEY }}

  release-please:
    runs-on: ubuntu-latest
    needs: [e2e]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_GH_TOKEN }}
          release-type: simple
  ci-validation:
    name: CI validation
    needs: [e2e, release-please]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Check jobs for errors
        uses: actions/github-script@v7
        with:
          script: |
            const checkJobsForErrors = require('./.github/workflows/js/check-for-errors.js');
            const jobs = ${{ toJSON(needs) }};
            checkJobsForErrors({ core, jobs });
