name: Create a release tag
run-name: ${{ github.actor }} creating a release tag

on:
  push:
    branches:
      - main
    paths:
      - website/**/*
      - .github/workflows/release.yaml
      - '!CHANGELOG.md'  
      
permissions:
  contents: write
  pull-requests: write      

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_GH_TOKEN }}
          release-type: simple  
